"""add webhook error tracking

Revision ID: 25e0532882b7
Revises: d4f5bab077d5
Create Date: 2026-05-19 14:04:33.857540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e0532882b7'
down_revision = 'd4f5bab077d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reconciliation_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.drop_column('last_reconciliation_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reconciliation_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_error')
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('last_reconciliation_at')

    # ### end Alembic commands ###
