"""add reconciliation timestamp

Revision ID: 4025b31effce
Revises: 
Create Date: 2026-05-14 10:51:20.138766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4025b31effce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reconciliation_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.drop_column('last_reconciliation_at')

    # ### end Alembic commands ###
