"""add webhook retry timestamp

Revision ID: d18c7552473c
Revises: 25e0532882b7
Create Date: 2026-05-19 14:24:53.965569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18c7552473c'
down_revision = '25e0532882b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_retry_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.drop_column('last_retry_at')

    # ### end Alembic commands ###
