"""Add webhook payload storage

Revision ID: d4f5bab077d5
Revises: 4025b31effce
Create Date: 2026-05-15 18:09:33.434309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f5bab077d5'
down_revision = '4025b31effce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=True))
        batch_op.alter_column('processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('payload')
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###
